### ISSUE TITLE
TypeError: estimate() got an unexpected keyword argument 'pipelines'

### ISSUE THREAD

**Issue by Vaunorage** [carefree0910/carefree-learn#11]
When running tutorial code :

```
#%%
import cflearn
from cfdata.tabular import TabularDataset

import cflearn

from cfdata.tabular import *

# prepare iris dataset
iris = TabularDataset.iris()
iris = TabularData.from_dataset(iris)
# split 10% of the data as validation data
split = iris.split(0.1)
train, valid = split.remained, split.split
x_tr, y_tr = train.processed.xy
x_cv, y_cv = valid.processed.xy
data = x_tr, y_tr, x_cv, y_cv

m = cflearn.make().fit(*data)
# Make label predictions
m.predict(x_cv)
# Make probability predictions
m.predict_prob(x_cv)
# Estimate performance
cflearn.estimate(x_cv, y_cv, pipelines=m)
```
We get :

```
                                     Traceback (most recent call last):
  File "C:\ProgramData\miniconda\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-78d46f42bbd0>", line 24, in <module>
    cflearn.estimate(x_cv, y_cv, pipelines=m)
TypeError: estimate() got an unexpected keyword argument 'pipelines'
```

**Comment by carefree0910** [comment]
Hi! It's my bad for not clarifying that some of the usages are only available through pip installing from source 😢 I'll update the `README.md` ASAP!

**Comment by carefree0910** [comment]
I've updated the `README.md`, hiding oridinary `pip install` method 😅

I know this is something bad but I'm busy working on new features, after which I'll release a new version! 🤣
