### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by jmrichardson** [carefree0910/carefree-learn#5]
Hi,

FYI, I got this error running the example:

```
import cflearn
from cfdata.tabular import TabularDataset

x, y = TabularDataset.iris().xy
m = cflearn.make().fit(x, y)
```

```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-7dea84d121c1>", line 5, in <module>
    m = cflearn.make().fit(x, y)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\cflearn\bases.py", line 860, in fit
    self._before_loop(x, y, x_cv, y_cv)
  File "D:\Anaconda3\envs\tipjar\lib\site-packages\cflearn\bases.py", line 829, in _before_loop
    self.cv_data, self.tr_data = self.tr_data.split(self._cv_split)
ValueError: too many values to unpack (expected 2)
```

Was able to fix by installing the latest:

`pip install -U git+https://github.com/carefree0910/carefree-learn.git`

**Comment by carefree0910** [comment]
Thanks for pointing out! This error comes from the backward compatible breaking caused by [`carefree-data`](https://github.com/carefree0910/carefree-data), so another solution is to re-install [`carefree-data`](https://github.com/carefree0910/carefree-data) to `0.1.5` 😉

> I'm not closing this issue in case other users face the same problem!
